//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDemos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class LibrarySetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static LibrarySetting defaultInstance = ((LibrarySetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LibrarySetting())));
        
        public static LibrarySetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public string ISerove {
            get {
                return ((string)(this["ISerove"]));
            }
            set {
                this["ISerove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13333")]
        public string cd {
            get {
                return ((string)(this["cd"]));
            }
            set {
                this["cd"] = value;
            }
        }
    }
}
